PPCMS2/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', RedirectView.as_view(url='account/login', permanent=False)),
    path('admin/', admin.site.urls),
    path('conference/', include('conference.urls')),
    path('account/', include('account.urls')),
    path('cfp/', include('cfp.urls')),
    re_path(r'^invitations/', include('invitations.urls', namespace='invitations')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if the DEBUG flag is true, then serve files. I need to serve these files using my webserver in production env.
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

cfp/urls.py
from django.urls import path, include
from .views import CFPView #CFPSearchResult

urlpatterns = [
    path('',  CFPView.as_view(), name='cfp-search'),
    #path('search/', CFPSearchResult.as_view(), name='cfp-search-result'),
]

conference/urls.py
from django.urls import path
from conference import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<uuid:pk>', views.PublicConferenceDetailView.as_view(), name='conference-details'),

    #Chair's URLs:
    path('create', views.ConferenceCreate.as_view(), name='conference-create'),
    path('manage/<uuid:pk>', views.ChairConferenceManageView.as_view(), name='conference-manage'),
    path('update/<uuid:pk>/', views.ConferenceUpdate.as_view(), name='conference-update'),
    path('delete/<uuid:pk>/', views.ConferenceDelete.as_view(), name='conference-delete'),
    path('next_phase/<uuid:pk>/', views.next_phase, name='next-phase'),

    path('submissions/<uuid:pk>/', views.ViewConferenceSubmissions.as_view(), name='view-submissions'),
    path('submission/<pk>', views.ChairSubmissionDetails.as_view(), name='chair-submission-details'),
    path('add_reviewer/<pk>/', views.AddAReviewer.as_view(), name='add-reviewer'),
    path('delete_reviewer/<submid>-<reviewerid>/', views.delete_reviewer, name='delete-reviewer'),

    path('reviewer/submissions_list/<uuid:pk>/', views.ReviewerAssignedSubmissions.as_view(),
         name='reviewer-assigned-submissions'),
    path('reviewer/submission_review/<submid>/', views.ReviewerSubmissionReview.as_view(),
         name='reviewer-submission-review'),
    path('reviewer/submission_reviews_and_discussions/<submid>/', views.ReviewerSubmissionReviewsAndDiscussions.as_view(),
         name='reviewer-submission-reviews-discussions'),

    path('invite/<uuid:pk>/', views.InvitePCMView.as_view(), name='invite-pcm'),
    path('invite/accept/<inviteid>', views.accept_invite, name='invite-pcm-accept'),
    path('invite/reject/<inviteid>', views.reject_invite, name='invite-pcm-reject'),

    #path('invite/success/<uuid:pk>/', views.InvitePCMView.as_view(), name='invitation-success'),

    #Author's URLs
    path('submit_a_paper/<uuid:pk>/', views.SubmissionCreate.as_view(), name='paper-submit'),
    path('my_submissions/', views.MySubmissionsList.as_view(), name='my-submissions'),
    path('my_submission/<pk>', views.MySubmissionDetails.as_view(), name='submission-details'),
    path('my_submission/update/<pk>', views.SubmissionUpdate.as_view(), name='submission-update'),
    path('my_submission/delete/<pk>', views.SubmissionDelete.as_view(), name='submission-delete'),


]

conference/models.py
from django.db import models
import uuid
from django.urls import reverse
from account.models import CustomUser

from datetime import timedelta
from django.db.models import Q
from django.conf import settings
from django.utils import timezone


class Conference(models.Model):
    """" This is the class for the conference model/table"""
    CID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False) #The Conference ID
    name = models.CharField(max_length=200, help_text='Enter the conference name') #The conference name
    acronym = models.CharField(max_length=50, help_text='Enter the Acronym of the conference', null=True) #The conference Acronym
    web_page = models.URLField(max_length=200, help_text='Enter the web page of your conference', default="") #The conference web page
    venue = models.CharField(max_length=200, help_text="Enter the venue of the conference", null=True) # Location
    city = models.CharField(max_length=200, help_text="Enter the city of the conference", default="") # Location
    country = models.CharField(max_length=200, help_text="Enter the country/region of the conference", default="") # Location
    start_date = models.DateField(help_text="Enter the start date of the conference", default=timezone.now, blank=True) # The conference data
    end_date = models.DateField(help_text="Enter the end date of the conference", default=timezone.now, blank=True) # The conference data
    phase = models.IntegerField(choices=((1,'registration'),(2,'submission'),(3,'review'),(4,'discussion'),(5,'notification')), default=1)
    chair = models.ForeignKey(CustomUser, on_delete=models.RESTRICT, related_name="conference_chair", default=1)

    # class Meta:
    #     permissions = (
    #         ('chair', 'Chair'),
    #         ('reviewer', 'Reviewer'),
    #     )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a particular instance of the model."""
        return reverse('conference-details', args=[str(self.CID)])


class ConferenceUserRole(models.Model):
    role_conference = models.ForeignKey(Conference, on_delete=models.CASCADE, related_name='role_conference')
    role_user = models.ForeignKey(CustomUser, on_delete=models.RESTRICT, related_name='role_user')

    roles_choices = {(1, 'chair'),
                     (2, 'reviewer'),
                     (3, 'author')}

    role = models.IntegerField(choices=roles_choices)

    class Meta:
        unique_together = ('role_conference', 'role_user', 'role')
        ordering = ['role']

    def __str__(self):
        return self.role_conference.name + '_' + self.role_user.first_name + '_' + self.get_role_display()


class ConferencePCMInvitationsManager(models.Manager):

    def get_expired(self):
        return self.filter(self.get_expired_query())

    def get_active(self):
        return self.exclude(self.get_expired_query())

    def get_expired_query(self):
        expiration_date = timezone.now() - timedelta(
            days=settings.INVITATION_EXPIRY)
        query = Q(accepted=True) | Q(invitation_date__lt=expiration_date)
        return query

    def delete_expired_confirmations(self):
        self.all_expired().delete()


class ConferencePCMInvitation(models.Model):
    invitee = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='invitation_invitee')
    inviter = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='invitation_inviter')
    invitation_date = models.DateField(default=timezone.now)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE, related_name='invitation_conference')
    role = models.IntegerField(choices=((1,'chair'),(2,'member'),), default=2)
    accepted = models.BooleanField(default=False)
    objects = ConferencePCMInvitationsManager()

    class Meta:
        unique_together = ('conference', 'invitee', 'role')

    def get_roles_str(self):
        if self.role == 1:
            return "chair"
        elif self.role == 2:
            return "PC member"


class ConferenceSubmission(models.Model):
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE, related_name='submission_conference')
    authors = models.ManyToManyField(CustomUser, related_name='submission_authors')
    title = models.CharField(max_length=200)
    abstract = models.TextField()
    submission_date = models.DateField(default=timezone.now)
    paper_file = models.FileField(upload_to='submissions/')
    reviewers = models.ManyToManyField(CustomUser, related_name='submission_reviewers')
    decision = models.IntegerField(choices=((1,'accept'),(2, 'reject')), null=True)

    # class Meta:
    #     permissions = (
    #         ('chair', 'Chair'),
    #         ('reviewer', 'Reviewer'),
    #         ('author', 'Author'),
    #     )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('submission-details', args=[self.id])


class ConferenceSubmissionReview(models.Model):
    review_conference = models.ForeignKey(Conference, on_delete=models.CASCADE, related_name='review_conference')
    review_submission = models.ForeignKey(ConferenceSubmission, on_delete=models.CASCADE, related_name='review_submission')
    review_reviewer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='review_reviewer' , default=1)
    review_text = models.TextField()
    scores = {
        (-2, 'strong reject'),
        (-1, 'weak reject'),
        (0, 'borderline paper'),
        (1, 'weak accept'),
        (2, 'strong accept'),
    }

    confidence = {
        (1, 'very low'),
        (2, 'low'),
        (3, 'normal'),
        (4, 'high'),
        (5, 'very high'),
    }
    review_score = models.IntegerField(choices=scores)
    review_confidence = models.IntegerField(choices=confidence)
    review_date_time = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['review_date_time']
        # permissions = (
        #     ('chair', 'Chair'),
        #     ('reviewer', 'Reviewer'),
        #     ('author', 'Author'),
        # )

    def __str__(self):
        return self.review_submission.title


class ConferenceSubmissionDiscussion(models.Model):
    discussion_conference = models.ForeignKey(Conference, on_delete=models.CASCADE, related_name='discussion_conference')
    discussion_submission = models.ForeignKey(ConferenceSubmission, on_delete=models.CASCADE,
                                          related_name='discussion_submission')
    discussion_reviewer = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='discussion_reviewer',
                                        default=1)
    discussion_text = models.TextField()
    discussion_date_time = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['discussion_date_time']
        # permissions = (
        #     ('chair', 'Chair'),
        #     ('reviewer', 'Reviewer'),
        #     ('author', 'Author'),
        # )

    def __str__(self):
        return self.discussion_submission.title

conference/forms.py
from django import forms
from account.models import CustomUser
from .models import ConferenceSubmission


class InvitePCMForm(forms.Form):
    invitee_email = forms.EmailField(max_length=254, help_text='Required. Provide a valid email address.', required=True)
    roles = (
        (1,'chair'),
        (2,'member'),
    )
    role = forms.ChoiceField(choices= roles)


class AddReviewersForm(forms.Form):

    class Meta:
        model = ConferenceSubmission
        fields = ['reviewers']

    reviewers = forms.ModelMultipleChoiceField(queryset=CustomUser.objects.all(), label= 'Reviewers')

    # def __init__(self, *args, **kwargs):
    #     super(AddReviewersForm, self).__init__(*args, **kwargs)
    #     group_name = kwargs.pop('group')
    #     self.fields['reviewers'].queryset= CustomUser.objects.filter(groups__name=group_name)

conference/templates/conference/chair/chair_add_reviewer_to_submission.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

conference/templates/conference/chair/chair_conference_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete conference</h1>

<p>Are you sure you want to delete the conference: {{ conference.name }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

conference/templates/conference/chair/chair_conference_create_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

conference/templates/conference/chair/chair_conference_details.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{ conference.name }}</h1>

    <p><strong>Acronym:</strong> {{ conference.acronym }}</p>
    <p><strong>Web page:</strong> {{ conference.web_page }}</p>
    <p><strong>Venue:</strong> {{ conference.venue }}</p>
    <p><strong>City:</strong> {{ conference.city }}</p>
    <p><strong>Country:</strong> {{ conference.country }}</p>
    <p><strong>Start date:</strong> {{ conference.start_date }}</p>
    <p><strong>End date:</strong> {{ conference.end_date }}</p>
    <p><strong>Submission deadline:</strong> {{ conference.submission_deadline }}</p>
    <p><strong>phase:</strong> {{ conference.get_phase_display }}</p>
    <p><strong>Program committee members:</strong>
        {% if PCM%}
            <ul>
                {% for member in PCM %}
                    <li> {{member}}</li>
                {% endfor %}
            </ul>
        {% else %}
            No program committee members have been added.
        {% endif %}
    </p>
    <p><strong>Chair:</strong> {{ conference.chair }}</p>

    <a href="{% url 'invite-pcm' pk=conference.CID %}"> <button> Manage program committee members</button></a>

      {% if conference.phase == 0 %}
        <a href="{% url 'next-phase' pk=conference.CID %}"> <button> Switch to submission phase </button></a>
      {% elif conference.phase == 1 %}
        <a href="{% url 'next-phase' pk=conference.CID %}"> <button> Switch to review phase</button> </a>
      {% elif conference.phase == 2 %}
        <a href="{% url 'next-phase' pk=conference.CID %}"> <button> Switch to discussion phase</button> </a>
      {% elif conference.phase == 3 %}
        <a href="{% url 'next-phase' pk=conference.CID %}"> <button> Switch to notification phase</button></a>
      {% endif %}


    <a href="{% url 'view-submissions' pk=conference.CID %}"> <button>  View submissions </button></a>
    <a href="{% url 'conference-delete' pk=conference.CID %}"> <button> Delete the conference</button> </a>

{% endblock %}

{% block sidebar_conferences %} {% endblock %}

conference/templates/conference/chair/chair_submission_details.html
{% extends "base_generic.html" %}

{% block content %}
 <h1> {{ submission_details.conference.name }}</h1>

  <p><strong>Title:</strong> {{ submission_details.title }}</p>
  <p><strong>Authors:</strong>
   {% for author in submission_details.authors.all %}
   {{author}}
   <br/>
   {% endfor %}
  </p>
  <p><strong>Abstract:</strong> {{ submission_details.abstract }}</p>
  <p><strong>File:</strong> <a href="{{ submission_details.paper_file.url }}"> download file</a></p>
  <p><strong>Submission date:</strong> {{ submission_details.submission_date }}</p>
  <p><strong>Reviewers:</strong>
  {% if submission_details.reviewers.all.count > 0 %}
   {% for reviewer in submission_details.reviewers.all%}
      <p> {{ reviewer }} <a href="{% url 'delete-reviewer' submid=submission_details.id reviewerid=reviewer.id %}"> Delete</a></p>
   {% endfor %}
  {% else %}
    No reviewers are assigned for this submission.
   {% endif %}
  </p>
  <p><a href="{% url 'add-reviewer' pk=submission_details.pk %}"> Assign reviewers</a></p>

    <br/>
    <strong> Reviews:</strong>
      {% for review in submission_details.review_submission.all %}
          <table border="1" style="width:400px">
              <tr><th colspan="2">Review {{ forloop.counter }}</th></tr>
              <tr><td style="width:60px"> Reviewer:</td> <td> {{review.review_reviewer}}</td></tr>
              <tr><td style="width:60px"> Review Date:</td> <td> {{review.review_date_time}}</td></tr>
              <tr><td style="width:60px"> Score:</td> <td> {{review.get_review_score_display}}</td></tr>
              <tr><td style="width:60px"> Expertise:</td> <td> {{review.get_review_confidence_display}}</td></tr>
              <tr><td style="width:60px"> Overall review:</td> <td> {{review.review_text}}</td></tr>
          </table>
          </br>
      {% endfor %}

    {% for discussion in  submission_details.discussion_submission.all %}
    <table border="1" style="width:400px">
        <tr><th colspan="2">Comment {{ forloop.counter }}</th></tr>
        <tr><td style="width:60px"> Reviewer:</td> <td> {{discussion.discussion_reviewer}}</td></tr>
        <tr><td style="width:60px"> Review Date:</td> <td> {{discussion.discussion_date_time}}</td></tr>
        <tr><td style="width:60px"> Overall review:</td> <td> {{discussion.discussion_text}}</td></tr>
    </table>
    </br>
    {% endfor %}

        <form action="" method="post">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="Submit">
        </form>


{% endblock %}

    {% block sidebar_conferences %} {% endblock %}

conference/templates/conference/chair/chair_submissions_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h2>Submissions:</h2>
  <p>{% if submissions_list %}</p>
    <table border="1" style="width:400px">
        <tr><th>Title</th> <th>Submission date</th></tr>
        {% for submission in submissions_list %}
          <tr>
            <td><a href="{% url 'chair-submission-details' pk=submission.pk %}">{{submission.title}}</a></td>
            <td>{{submission.submission_date}}</td>
          </tr>
        {% endfor %}
    </table>
  {% else %}
    <p>You do not have any submission.</p>
  {% endif %}
{% endblock %}